name: Java CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - uses: actions/upload-artifact@v4
        with:
          name: vscode-swf-debug
          path: distribution/target/vscode-swf-debug/vscode-swf-debug/vscode-swf-debug-*.vsix
          if-no-files-found: error
